server:
  port: 8091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123465
    url: jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false

justauth:
  enabled: true
  type:
    GITEE:
      client-id: 41367d440b7cc673691273e7d2182c0cb065c83e07a8a0a4abc3e1c213555a44
      client-secret: 696287623efa60478b4a63eef55ab807b93403fc645c345410d61fc0795e93a6
      redirect-uri: http://127.0.0.1:8091/oauth/gitee/callback