server:
  port: 8091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123465
    url: jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true

justauth:
  enabled: true
  type:
    GITEE:
      client-id: 41367d440b7cc673691273e7d2182c0cb065c83e07a8a0a4abc3e1c213555a44
      client-secret: 696287623efa60478b4a63eef55ab807b93403fc645c345410d61fc0795e93a6
      redirect-uri: http://127.0.0.1:8080/oauth/GITEE/callback

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  # 配置枚举 支持通配符 * 或者 ; 分割
  type-enums-package: cn.yiidii.mybatis.enumeration;cn.yiidii.todo.model.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  sql-log:
    enable: true